# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

# no PR builds
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: minnasmile-azurecr
- group: ms-survey-api
- name: dockerId
  value: minnasmile
- name: imageName
  value: ms-survey-api:latest
- name: dockerUrl
  value: $(dockerId).azurecr.io

steps:
- script: |
    docker build  -f Dockerfile -t $(dockerUrl)/$(imageName) .
    docker login -u $(dockerId) -p $(dockerPassword) $(dockerUrl)
    docker push $(dockerUrl)/$(imageName)
  displayName: Build Docker image
